version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

  app:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "80:5050"   # map host port 80 → container port 5050
      - "5050:5050"  # map the host port 5050 -> container port so that locally users canrequest using the http:localhost:5050 also when using curl 
    volumes:
      - .:/app:cached
    command: >
      gunicorn -w 4 -b 0.0.0.0:${PORT} main:app

volumes:
  db_data:

